title: "Ode to Gradients"
description: "Manifold tangents made tangible"

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://christiancosgrove.com" # change this to the base hostname & protocol for your site

google_analytics: "UA-99827000-1"
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty
comments: true

# social
author: "Christian Cosgrove"
github: 
  owner_url: "https://github.com/christiancosgrove"
disqus:
  shortname: christiancosgrove
